### ISSUE TITLE
Which repositories will live under the python-http organization?

### ISSUE THREAD

**Issue by lovelydinosaur** [python-http/discussions#2]
What are our thoughts on this org. wrt project repositories?

Should we be considering having `http3` (under whatever actual branding) live under this org?
Same question for `h2`/`h11` and similar projects?

**Comment by pgjones** [comment]
Regarding `h2` and `h11`, I think the Hyper name is well established and associated with them so I'm not sure they should move. What would they miss out on though by staying where they are?

**Comment by njsmith** [comment]
python-hyper is somewhat moribund as an organization. Organisations are nice because they let you amortize the work of setting up social infrastructure like membership policies, contributing guidelines, code of conduct, automation, etc. This stuff's a time sink and the more projects can share the load, the better quality they'll all be. That's why I moved h11 there is the first place. But more recently I've vaguely considered moving h11 to the trio org, not because it's particularly tied to trio, but just because that infrastructure's more actively maintained.

One vision for the future of python-http would be to consolidate all the major projects under the umbrella: urllib3, h11/h2, requests, etc.

**Comment by sethmlarson** [comment]
@njsmith nails it here. Would be interesting to see if we could get a singular project template in terms of automation and tooling that all projects use to reduce the maintenance and learning curve for new contributors.

It took a long time to get urllib3 running unit tests, integration tests on release candidates, and automatically deploying to PyPI from Travis. Would be great to standardize it for many packages use.
